model:
  name: RandomForestClassifier
  config:
      max_depth: 6
      min_samples_split: 3
      min_samples_leaf: 1
data:
  features: {'Sex':'cat', 'Age':'num'}
  target: {'Survived':'cat'}
  train_id_list: null
  test_id_list: null
